### ISSUE TITLE
**Issue: Unable to Open "version" File in NetMHCpan - File Not Found & TypeError during pVACseq Execution**

### ISSUE THREAD

**Issue by chumawinnie** [dmnfarrell/epitopepredict#13]
Hi NetMHCpan team,

I encountered an issue while trying to run the NetMHCpan prediction via the pVACseq pipeline. The following error occurs:

```
Generating Variant Peptide FASTA and Key Files - Epitope Length 8 - Entries 11801-11910
Generating Variant Peptide FASTA and Key Files - Epitope Length 9 - Entries 11801-11910
Generating Variant Peptide FASTA and Key Files - Epitope Length 10 - Entries 11801-11910
Completed
Making binding predictions on Allele HLA-A*31:01 and Epitope Length 8 with Method NetMHCpan - File /home/obiorach/test-work-sarek/neoantigen-output/MHC_Class_I/tmp/Patient_3_Tumour.netmhcpan.HLA-A*31:01.8.tsv_1-200
Unable to open(r) file /home/obiorach/netMHCpan_complete/netMHCpan-4.1/Linux_x86_64/bin/netMHCpan/data/version
2024-10-16:14:47:06,812 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
```

It keeps repeating:

```
Unable to open(r) file /home/obiorach/netMHCpan_complete/netMHCpan-4.1/Linux_x86_64/bin/netMHCpan/data/version
2024-10-16:14:47:07,621 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
```

Finally, it throws a critical error:

```
CRITICAL:pymp:An exception occurred in thread 0: (<class 'TypeError'>, a bytes-like object is required, not 'NoneType').
Traceback (most recent call last):
  File "/home/obiorach/miniconda3/envs/pvacseq-env/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 357, in call_iedb
    pvactools.lib.call_iedb.main(arguments)
  File "/home/obiorach/miniconda3/envs/pvacseq-env/lib/python3.8/site-packages/pvactools/lib/call_iedb.py", line 53, in main
    tmp_output_filehandle.write(response_text)
TypeError: a bytes-like object is required, not 'NoneType'
```

The problem seems to be related to the inability to access the "version" file located at `/home/obiorach/netMHCpan_complete/netMHCpan-4.1/Linux_x86_64/bin/netMHCpan/data/version`.

Here’s what I have tried:
- Manually creating the version file with content "4.1" in the correct path.
- Confirming the symbolic links are in place and pointing to the correct executable.
- Testing manually by invoking `netMHCpan`, which still results in the same missing version file issue.

**Environment:**
- pVACseq environment running through Conda.
- NetMHCpan version: 4.1
- The NetMHCpan executable path is correctly linked.

Could you please provide some guidance on how to resolve this issue?

Thanks in advance for your help!

---

**Comment by dmnfarrell** [comment]
I think you have the wrong repository here. this library is not part of pVACseq as far as I know.
