### ISSUE TITLE
change function names on notebook

### ISSUE THREAD

**Issue by carlomazzaferro** [dmnfarrell/epitopepredict#2]
Quick remark, probably not too significant. fasta_to_dataframe should be renamed fasta2Dataframe (and whatever other function that has changed names) to reflect source code.

**Comment by dmnfarrell** [comment]
Thanks. Actually it's the other way round. I am renaming all module level functions to use underscore/no caps. So the new name is fasta_to_dataframe. Only the class methods still have camelCase. The notebooks are being changed accordingly as I go along. I didn't think anyone was looking... ;)

**Comment by carlomazzaferro** [comment]
Thanks for clarification. I'll keep myself posted on progress/changes here. There are not too many out-of-the-box epitope prediction packages for Python and yours seems to fit the needs of our lab pretty neatly!
