### ISSUE TITLE
netMHCIIpan parsing error

### ISSUE THREAD

**Issue by partrita** [dmnfarrell/epitopepredict#9]
my code is 
```python
reload(base)
length = 9
p1 = base.get_predictor('netmhciipan')
b2 = p1.predict_sequences(my_seq, alleles=m2_alleles, length=length, threads=16)
b2
```

1-log50k(aff) | Affinity | allele | core | name | peptide | pos | rank | score
-- | -- | -- | -- | -- | -- | -- | -- | --
0.000001 | 95.00 | HLA-AASSGLMTK | Sequence | 0 | 0 | 186 | 1.0 | 95.0
0.000001 | 95.00 | HLA-AKGQPREPQ | Sequence | 0 | 0 | 324 | 1.0 | 95.0
0.000001 | 95.00 | HLA-AKTKPREEQ | Sequence | 0 | 0 | 272 | 1.0 | 95.0
0.000001 | 95.00 | HLA-ALHNHYTQK | Sequence | 0 | 0 | 416 | 1.0 | 95.0
0.000004 | 95.00 | HLA-ALPAPIEKT | Sequence | 0 | 0 | 312 | 1.0 | 95.0
0.000008 | 95.00 | HLA-YSKLTVDKS | Sequence | 0 | 0 | 392 | 1.0 | 95.0
0.000003 | 95.00 | HLA-YTCAASSGL | Sequence | 0 | 0 | 183 | 1.0 | 95.0
0.000002 | 95.00 | HLA-YTLPPSRDE | Sequence | 0 | 0 | 334 | 1.0 | 95.0
0.000007 | 95.00 | HLA-YTQKSLSLS | Sequence | 0 | 0 | 421 | 1.0 | 95.0
0.000002 | 95.00 | HLA-YVDGVEVHN | Sequence | 0 | 0 | 263 | 1.0 | 95.0

allele and core seems wrong.

**Comment by dmnfarrell** [comment]
what version of netmhciipan are you using?

**Comment by partrita** [comment]
>  what version of netmhciipan are you using?

newest version, which is 4.1

by the way, I fix the error by duck-taping.
